name: ConanPackages post-push
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Open conan packages storage
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          pass: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command: |
            tmux kill-session -t conan_server || true
            tmux new-session -d -s conan_server "conan_server"